export const typeColorsMap = {
    normal: "#A8A77A",
    fire: "#EE8130",
    water: "#6390F0",
    electric: "#F7D02C",
    grass: "#7AC74C",
    ice: "#96D9D6",
    fighting: "#C22E28",
    poison: "#A33EA1",
    ground: "#E2BF65",
    flying: "#A98FF3",
    psychic: "#F95587",
    bug: "#A6B91A",
    rock: "#B6A136",
    ghost: "#735797",
    dragon: "#6F35FC",
    dark: "#705746",
    steel: "#B7B7CE",
    fairy: "#D685AD"
};

export const weaknessesArray = {
    normal: ['fighting'],
    fighting: ['flying', 'psychic', 'fairy'],
    flying: ['rock', 'ice', 'electric'],
    poison: ['ground', 'psychic'],
    ground: ['water', 'grass', 'ice'],
    rock: ['fighting', 'ground', 'steel', 'water', 'grass'],
    bug: ['flying', 'fire', 'rock'],
    ghost: ['ghost', 'dark'],
    steel: ['fighting', 'fire', 'ground'],
    fire: ['rock', 'ground', 'water'],
    water: ['electric', 'grass'],
    grass: ['flying', 'poison', 'bug', 'ice', 'fire'],
    electric: ['ground'],
    psychic: ['bug', 'ghost', 'dark'],
    ice: ['steel', 'fire', 'fighting', 'rock'],
    dragon: ['ice', 'dragon','fairy'],
    dark: ['fighting', 'bug', 'fairy'],
    fairy: ['poison', 'steel']
};

export const strengthsArray = {
    normal: [],
    fighting: ['normal', 'rock', 'steel', 'ice', 'dark'],
    flying: ['fighting', 'bug', 'grass'],
    poison: ['grass', 'fairy'],
    ground: ['poison', 'rock', 'steel', 'fire', 'electric'],
    rock: ['flying', 'bug', 'fire', 'ice'],
    bug: ['grass', 'psychic', 'dark'],
    ghost: ['ghost', 'psychic'],
    steel: ['rock', 'ice', 'fairy'],
    fire: ['bug', 'steel', 'grass', 'ice'],
    water: ['ground', 'rock', 'fire'],
    grass: ['ground', 'rock', 'water'],
    electric: ['flying', 'water'],
    psychic: ['fighting', 'poison'],
    ice: ['flying', 'ground', 'grass', 'dragon'],
    dragon: ['dragon'],
    dark: ['ghost', 'psychic'],
    fairy: ['fighting', 'dragon', 'dark']
};

export const resistanceArray = {
    normal: ['ghost'],
    fighting: ['bug', 'rock', 'dark'],
    flying: ['fighting', 'bug', 'grass', 'ground'],
    poison: ['fighting', 'poison', 'grass', 'fairy'],
    ground: ['poison', 'rock', 'electric'],
    rock: ['normal', 'flying', 'poison', 'fire'],
    bug: ['fighting', 'ground', 'grass'],
    ghost: ['poison', 'bug', 'normal', 'fighting'],
    steel: ['normal', 'flying','poison', 'rock', 'bug', 'steel', 'grass', 'psychic', 'ice', 'dragon', 'fairy'],
    fire: ['bug', 'steel', 'fire', 'grass', 'ice'],
    water: ['steel', 'fire', 'water', 'ice'],
    grass: ['ground', 'water', 'grass', 'electric'],
    electric: ['flying', 'steel', 'electric'],
    psychic: ['fighting', 'psychic'],
    ice: ['ice'],
    dragon: ['fire', 'water', 'grass', 'electric'],
    dark: ['ghost', 'dark', 'psychic'],
    fairy: ['fighting', 'bug', 'dark', 'dragon']
};
