import { Inter, Lalezar } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: '--font-inter'});
const lalezar = Lalezar({ weight: ["400"], subsets: ["latin"], variable: '--font-lalezar'});

export const metadata = {
  title: "Pokedexplorer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/icon.ico" sizes="any" />
      <body className={`${inter.variable} ${lalezar.variable}`}>{children}</body>
    </html>
  );
}
